### PR TITLE
add french translation

### PR DESCRIPTION
**Pull request by caliendojulien**
add french translation to task_description and task_short_description

### CODE REVIEW

**Comment by oduvan** [comment]
from what I see only task_short_description.html have been translated everything else is still in English

**Comment by caliendojulien** [comment]
fr/info/task_description.html added. I'll translate fr/hints/oduvan.html soon

**Comment by oduvan** [comment]
You may simply do not add original files if those are not translated. In that case system will use original anyway.

**Comment by oduvan** [comment]
Thanks for your translation

**Pull request merged**
